version: "3"

services:

  gunicorn:
    build:
      context: dash
      dockerfile: ./Dockerfile
    expose:
      - 80
    volumes:
      - ./dash:/dash
      - ./data:/data
      - ./blog:/blog
      - ./shared_config:/shared_config
      - ./.git:/.git/:ro
    networks:
      - default

# VARNISH HERE

  cache:
    image: nginx
    ports:
      - 80:80
    networks:
      - web
      - default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # PUT TRAEFIK LABELS HERE


networks:
  web:
    external: true
